[2024-11-12T19:49:32.032+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T19:49:32.063+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Stock_data_analysis_lab2utl.insert_stock_prices scheduled__2024-11-11T17:00:00+00:00 [queued]>
[2024-11-12T19:49:32.073+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Stock_data_analysis_lab2utl.insert_stock_prices scheduled__2024-11-11T17:00:00+00:00 [queued]>
[2024-11-12T19:49:32.074+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-11-12T19:49:32.092+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): insert_stock_prices> on 2024-11-11 17:00:00+00:00
[2024-11-12T19:49:32.101+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Stock_data_analysis_lab2utl', 'insert_stock_prices', 'scheduled__2024-11-11T17:00:00+00:00', '--job-id', '182', '--raw', '--subdir', 'DAGS_FOLDER/utl.py', '--cfg-path', '/tmp/tmp43d7mf0e']
[2024-11-12T19:49:32.104+0000] {standard_task_runner.py:91} INFO - Job 182: Subtask insert_stock_prices
[2024-11-12T19:49:32.104+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=272) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-12T19:49:32.105+0000] {standard_task_runner.py:63} INFO - Started process 296 to run task
[2024-11-12T19:49:32.158+0000] {task_command.py:426} INFO - Running <TaskInstance: Stock_data_analysis_lab2utl.insert_stock_prices scheduled__2024-11-11T17:00:00+00:00 [running]> on host 16d7368eac06
[2024-11-12T19:49:32.520+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Utkarsh Tripathi' AIRFLOW_CTX_DAG_ID='Stock_data_analysis_lab2utl' AIRFLOW_CTX_TASK_ID='insert_stock_prices' AIRFLOW_CTX_EXECUTION_DATE='2024-11-11T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-11T17:00:00+00:00'
[2024-11-12T19:49:32.522+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T19:49:32.542+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.0, Python Version: 3.12.3, Platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2024-11-12T19:49:32.544+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-11-12T19:49:34.131+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-12T19:53:09.584+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7f3e82f0ad20>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /queries/v1/query-request?requestId=7e758bce-6d0d-44c4-8282-e209e45b4a5c&clientStartTime=1731441161287&retryCount=1&retryReason=None&request_guid=6dbefd7a-73b4-48ed-b958-d6a42e78a6fb
[2024-11-12T19:53:52.354+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-12T19:53:52.356+0000] {logging_mixin.py:188} INFO - Data inserted successfully.
[2024-11-12T19:53:52.357+0000] {connection.py:762} INFO - closed
[2024-11-12T19:53:52.414+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-11-12T19:53:52.483+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-12T19:53:52.484+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T19:53:52.500+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Stock_data_analysis_lab2utl, task_id=insert_stock_prices, run_id=scheduled__2024-11-11T17:00:00+00:00, execution_date=20241111T170000, start_date=20241112T194932, end_date=20241112T195352
[2024-11-12T19:53:52.562+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-12T19:53:52.588+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-12T19:53:52.594+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
